### ISSUE TITLE
[BUG]Quick reference breaks

### ISSUE THREAD

**Issue by jiajiala** [RyotaUshio/obsidian-better-note-composer#2]
[[Test#^J20241113104446]]
References like this break when they are moved

**Comment by RyotaUshio** [comment]
In my quick test, they don't break.
Please provide more concrete steps to reproduce your issue (e.g. create md files A & B with these contents, and then select this portion of text, and then trigger the command "..."), otherwise I will not be able to track it.

**Comment by jiajiala** [comment]
It was really good when I operated it again, maybe it was my wrong operation, sorry to disturb
I'll come back if it happens again

Thanks again for this plugin, it's really awesome and easy to use!!
